from PIL import Image
x = Image.open("gg.jpg")
print("ширина",x.width)
print("длина",x.height)
print("название: попугай")
x.close()
print()
from PIL import Image
a = Image.open("m.jpg")
print("ширина",a.width)
print("длина",a.height)
print("название: пузырь в руках")
a.close()
print()
from PIL import Image
f = Image.open("f.jpg")
print("ширина",f.width)
print("длина",f.height)
print("название: поле")
f.close()
print()
from PIL import Image
s = Image.open("d.jpg")
print("ширина",s.width)
print("длина",s.height)
print("название: река в лесу")
s.close()
print()
from PIL import Image
w = Image.open("ai.jpg")
print("ширина",w.width)
print("длина",w.height)
print("название: цветок и капля")
w.close()
